name: Build and test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:

  build_test:
    strategy:
      matrix:
        node-version: [20, 22, 24]

    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout the Repository
      uses: actions/checkout@v4
      
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Install dependencies
      run: npm install
      
    - name: Run Integration tests
      run: npm test
    
  # deploy:
  #   needs: build_test
  #   runs-on: ubuntu-latest
  #   if : github.ref == 'refs/heads/main'
  #   steps:
  #     - name: Deploy to production
  #       uses: JorgeLNJunior/render-deploy@v1.5.0
  #       with:
  #         service_id: ${{ secrets.SERVICE_ID }}
  #         api_key: ${{ secrets.RENDER_TOKEN }}
  #         wait_deploy: true